csfd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("csfd_app.urls", namespace="csfd_app"))
]

csfd_app/urls.py
from django.urls import path

from csfd_app.views import Homepage, SearchView, actor_detail, movie_detail, ActorsList, MoviesList

app_name = "csfd_app"

urlpatterns = [
    path("", Homepage.as_view(), name="homepage"),
    path("result/", SearchView.as_view(), name="result"),
    path("actors/", ActorsList.as_view(), name="actors"),
    path("movies/", MoviesList.as_view(), name="movies"),
    path("actor/<int:actor_id>/", actor_detail, name="actor-detail"),
    path("movie/<int:movie_id>/", movie_detail, name="movie-detail"),
]

csfd_app/models.py
from django.db import models


class Movies(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Actors(models.Model):
    name = models.CharField(max_length=100)
    movies = models.ManyToManyField(Movies, related_name="actors")

    def __str__(self):
        return self.name

csfd_app/forms.py
from django import forms


class SearchForm(forms.Form):
    q = forms.CharField(label="Hledat", max_length=50)

csfd_app/views.py
from django.db.models import Q, Model
from django.shortcuts import render
from django.views.generic import FormView, ListView, DetailView

from csfd_app.forms import SearchForm
from csfd_app.models import Actors, Movies


class Homepage(FormView):
    template_name = "homepage.html"
    form_class = SearchForm


class SearchView(ListView, FormView):
    template_name = "search_results.html"
    form_class = SearchForm
    model = Actors

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Actors.objects.filter(name__icontains=query)
        return object_list

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data(*args, **kwargs)

        query = self.request.GET.get('q')
        movies = Movies.objects.filter(title__icontains=query)

        context['movies_list'] = movies
        return context


def actor_detail(request, actor_id):
    actor = Actors.objects.get(id=actor_id)
    # movies = Movies.objects.filter(actors=actor)
    movies = actor.movies.all()
    context = {
        "actor": actor,
        "movies": movies
    }
    return render(request, 'actor_detail.html', context=context)


def movie_detail(request, movie_id):
    movie = Movies.objects.get(id=movie_id)
    actors = movie.actors.all()
    context = {
        "movie": movie,
        "actors": actors
    }
    return render(request, 'movie_detail.html', context=context)


class MoviesList(ListView):
    template_name = "movies_list.html"
    queryset = Movies.objects.all().order_by("title")
    context_object_name = "movies"


class ActorsList(ListView):
    template_name = "actors_list.html"
    queryset = Actors.objects.all().order_by("name")
    context_object_name = "actors"

csfd_app/templates/actor_detail.html
{% extends "base.html" %}

{% block content %}

<h2>{{ actor.name }}</h2>
<ul>
    {% for movie in movies %}
        <li>  <a href="{% url "csfd_app:movie-detail" movie.pk %}"> {{ movie.title }} </a> </li>
    {% endfor %}
</ul>

{% endblock content %}

csfd_app/templates/actors_list.html
{% extends "base.html" %}

{% block content %}

<h1>Seznam všech herců A-Z</h1>

<ul>
    {% for actor in actors %}
        <li> <a href="{% url "csfd_app:actor-detail" actor.pk %}"> {{ actor.name }} </a> </li>
    {% endfor %}
</ul>

{% endblock content %}

csfd_app/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ČSFD scrape web</title>
    <style>
* {
  box-sizing: border-box;
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;
  height: 300px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

</head>
<body>
<nav>
    <a href="{% url "csfd_app:homepage" %}">Homepage</a> |
    <a href="{% url "csfd_app:movies" %}">Seznam všech filmů</a> |
    <a href="{% url "csfd_app:actors" %}">Seznam všech herců</a>
</nav>
        {% block content %}
        {% endblock content%}
</body>
</html>

csfd_app/templates/homepage.html
{% extends "base.html" %}

{% block content %}
    <br><br>

<form action="{% url 'csfd_app:result' %}" method="get">
    {{ form }}
    <button type="submit">Hledat</button>
</form>

{% endblock content %}

csfd_app/templates/movie_detail.html
{% extends "base.html" %}

{% block content %}

<h2>Název filmu: {{ movie.title }}</h2>
Ve filmu hrají:
<ul>
    {% for actor in actors %}
        <li> <a href="{% url "csfd_app:actor-detail" actor.pk %}"> {{ actor.name }} </a> </li>
    {% endfor %}
</ul>

{% endblock content %}

csfd_app/templates/movies_list.html
{% extends "base.html" %}

{% block content %}

<h1>Seznam všech filmů A-Z:</h1>

<ul>
    {% for movie in movies %}
        <li>  <a href="{% url "csfd_app:movie-detail" movie.pk %}"> {{ movie.title }} </a> </li>
    {% endfor %}
</ul>

{% endblock content %}

csfd_app/templates/search_results.html
{% extends "base.html" %}

{% block content %}
    <br><br>
<form action="{% url 'csfd_app:result' %}" method="get">
    {{ form }}
    <button type="submit">Hledat</button>
</form>
   <br><br>

<div class="row">
    <div class="column">
        <h2> Nalezení herci: </h2>
        <ul>
            {% for actor in object_list %}
                <li><a href="{% url "csfd_app:actor-detail" actor.pk %}"> {{ actor.name }} </a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="column">
        <h2> Nalezené filmy: </h2>
            <ul>
                {% for movie in movies_list %}
                    <li><a href="{% url "csfd_app:movie-detail" movie.pk %}"> {{ movie.title }} </a></li>
                {% endfor %}
            </ul>
    </div>
</div>
{% endblock content %}